# Generated by Django 5.2.8 on 2025-11-30 06:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_alter_assignment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="file"
            ),
        ),
    ]
