# Generated by Django 5.2.8 on 2025-12-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_alter_assignment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("graded", "Graded"),
                    ("returned", "Returned for Revision"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
